__merge__: ../../api/comp_metric.yaml
functionality:
  name: mean_cosine_sim
  info:
    metrics:
      - name: mean_cosine_sim
        label: Mean Cosine Similarity
        summary: The mean of cosine similarities per row (perturbation).
        description: |
          The **Mean Cosine Similarity** is computed as follows:

          $$
          \textrm{Mean-Cosine} = \frac{1}{R}\sum_{i=1}^R\frac{\mathbf{y}_i\cdot \mathbf{\hat{y}}_i}{\|\mathbf{y}_i\| \|\mathbf{\hat{y}}_i\|}
          $$

          where $(R)$ is the number of scored rows, and $(\mathbf{y}_i)$ and $(\mathbf{\hat{y}}_i)$ are the actual and predicted values, respectively, for row $(i)$.
        repository_url: null
        documentation_url: null
        min: -1
        max: 1
        maximize: true
      - name: mean_cosine_sim_clipped_0001
        label: Mean Cosine Similarity clipped at 0.0001
        summary: The mean of cosine similarities per row (perturbation). Values are clipped to 0.0001 adjusted p-values.
        description: This metric is the same as `mean_cosine_sim`, but with the values clipped to [-log10(0.0001), log10(0.0001)].
        repository_url: null
        documentation_url: null
        min: -1
        max: 1
        maximize: true
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]