__merge__: ../../api/comp_metric.yaml
functionality:
  name: mean_cosine_sim
  info:
    metrics:
      - name: mean_cosine_sim
        label: Mean Cosine Similarity
        summary: The mean of cosine similarities per row (perturbation).
        description: |
          We use the **Mean Cosine Similarity** to score submissions, computed as follows:

          $$
          \textrm{Mean-Cosine} = \frac{1}{R} \sum_{i=1}^R \frac{\mathbf{y}_i \cdot \mathbf{\hat{y}}_i}{\|\mathbf{y}_i\| \|\mathbf{\hat{y}}_i\|}
          $$

          where $\\(R\\)$ is the number of scored rows, and $\\(\mathbf{y}_i\\)$ and $\\(\mathbf{\hat{y}}_i\\)$ are the actual and predicted values, respectively, for row $\\(i\\)$.
        repository_url: null
        documentation_url: null
        min: -1
        max: 1
        maximize: true
      - name: mean_cosine_sim_clipped_05
        label: Mean Cosine Similarity clipped at 0.5
        summary: The mean of cosine similarities per row (perturbation). Values are clipped to 0.5 adjusted p-values.
        description: |
          We use the **Mean Cosine Similarity** to score submissions, computed as follows:

          $$
          \textrm{Mean-Cosine} = \frac{1}{R} \sum_{i=1}^R \frac{\mathbf{y}_i \cdot \mathbf{\hat{y}}_i}{\|\mathbf{y}_i\| \|\mathbf{\hat{y}}_i\|}
          $$

          where $\\(R\\)$ is the number of scored rows, and $\\(\mathbf{y}_i\\)$ and $\\(\mathbf{\hat{y}}_i\\)$ are the actual and predicted values, respectively, for row $\\(i\\)$.
        repository_url: null
        documentation_url: null
        min: -1
        max: 1
        maximize: true
      - name: mean_cosine_sim_clipped_01
        label: Mean Cosine Similarity clipped at 0.1
        summary: The mean of cosine similarities per row (perturbation). Values are clipped to 0.1 adjusted p-values.
        description: |
          We use the **Mean Cosine Similarity** to score submissions, computed as follows:

          $$
          \textrm{Mean-Cosine} = \frac{1}{R} \sum_{i=1}^R \frac{\mathbf{y}_i \cdot \mathbf{\hat{y}}_i}{\|\mathbf{y}_i\| \|\mathbf{\hat{y}}_i\|}
          $$

          where $\\(R\\)$ is the number of scored rows, and $\\(\mathbf{y}_i\\)$ and $\\(\mathbf{\hat{y}}_i\\)$ are the actual and predicted values, respectively, for row $\\(i\\)$.
        repository_url: null
        documentation_url: null
        min: -1
        max: 1
        maximize: true
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [ fastparquet ]
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]