functionality:
  name: split_dataset
  namespace: dge_perturbation_prediction/process_dataset
  info:
    type: process_dataset
    type_info:
      label: Split dataset
      summary: Split dataset into training and test parquet files
      description: |
        Split dataset into training and test parquet files.
  arguments:
    - name: --input
      type: file
      required: true
      direction: input
      example: resources/neurips-2023-data/de.h5ad
    - name: --output_train
      type: file
      required: true
      direction: output
      example: resources/neurips-2023-data/de_train.parquet
    - name: --output_test
      type: file
      required: true
      direction: output
      example: resources/neurips-2023-data/de_test.parquet
    - name: --output_id_map
      type: file
      required: true
      direction: output
      example: resources/neurips-2023-data/id_map.csv
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    # doesn't want to work with 'base_python:1.0.2'
    # image: ghcr.io/openproblems-bio/base_python:1.0.2
    image: python:3.12
    setup:
      - type: python
        packages: [ fastparquet, anndata, pandas ]
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
