__merge__: ../../api/comp_control_method.yaml
functionality:
  name: mean_outcome
  info:
    label: Mean outcome for a gene
    summary: Baseline method that returns mean of gene's outcomes
    description: |
      Baseline method that predicts for a gene the mean of its outcomes of all samples.
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.2
    setup:
      - type: python
        packages: [ fastparquet ]
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]