functionality:
  name: "lgc_ensemble_predict"
  namespace: "methods"
  version: "build-main"
  arguments:
  - type: "file"
    name: "--train_data_aug_dir"
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--model_files"
    info: null
    example:
    - "model.pt"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ";"
    dest: "par"
  - type: "file"
    name: "--id_map"
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  - type: "file"
    path: "../lgc_ensemble_helpers/helper_classes.py"
  - type: "file"
    path: "../lgc_ensemble_helpers/helper_functions.py"
  - type: "file"
    path: "../lgc_ensemble_helpers/models.py"
  - type: "file"
    path: "../lgc_ensemble_helpers/predict.py"
  - type: "file"
    path: "../lgc_ensemble_helpers/prepare_data.py"
  - type: "file"
    path: "../lgc_ensemble_helpers/train.py"
  - type: "file"
    path: "../lgc_ensemble_helpers/divisor_finder.py"
  - type: "file"
    path: "../../utils/anndata_to_dataframe.py"
  info: null
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/openproblems-bio/base_pytorch_nvidia:1.0.4"
  target_organization: "openproblems-bio/task_perturbation_prediction"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args:
  - "--shm-size=2g"
  target_image_source: "https://github.com/openproblems-bio/task_perturbation_prediction"
  setup:
  - type: "python"
    user: false
    packages:
    - "torch==2.1.1"
    - "--index-url"
    - "https://download.pytorch.org/whl/cu121"
    upgrade: true
  - type: "python"
    user: false
    packages:
    - "fastparquet"
    - "pandas==2.1.3"
    - "pyarrow==14.0.1"
    - "tqdm==4.66.1"
    - "scikit-learn==1.3.2"
    - "transformers==4.35.2"
    - "matplotlib==3.8.2"
    - "torch-summary"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "native"
  id: "native"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "hightime"
    - "veryhighmem"
    - "highcpu"
    - "highsharedmem"
    - "gpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task_perturbation_prediction/task_perturbation_prediction/src/methods/lgc_ensemble_predict/config.vsh.yaml"
  platform: "native"
  output: "/home/runner/work/task_perturbation_prediction/task_perturbation_prediction/target/native/methods/lgc_ensemble_predict"
  executable: "/home/runner/work/task_perturbation_prediction/task_perturbation_prediction/target/native/methods/lgc_ensemble_predict/lgc_ensemble_predict"
  viash_version: "0.8.6"
  git_commit: "a623d3ad92e82dc099ecaf024de153237d275931"
  git_remote: "https://github.com/openproblems-bio/task_perturbation_prediction"
