functionality:
  name: "mean_outcome"
  namespace: "control_methods"
  version: "main_build"
  arguments:
  - type: "file"
    name: "--de_train"
    info:
      label: "DE train"
      summary: "Differential expression results for training."
      file_type: "parquet"
      columns:
      - name: "cell_type"
        type: "string"
        description: "The annotated cell type of each cell based on RNA expression."
        required: true
      - name: "sm_name"
        type: "string"
        description: "The primary name for the (parent) compound (in a standardized\
          \ representation)\nas chosen by LINCS. This is provided to map the data\
          \ in this experiment to \nthe LINCS Connectivity Map data.\n"
        required: true
      - name: "sm_lincs_id"
        type: "string"
        description: "The global LINCS ID (parent) compound (in a standardized representation).\n\
          This is provided to map the data in this experiment to the LINCS Connectivity\n\
          Map data.\n"
        required: true
      - name: "SMILES"
        type: "string"
        description: "Simplified molecular-input line-entry system (SMILES) representations\
          \ of the\ncompounds used in the experiment. This is a 1D representation\
          \ of molecular\nstructure. These SMILES are provided by Cellarity based\
          \ on the specific\ncompounds ordered for this experiment.\n"
        required: true
      - name: "split"
        type: "string"
        description: "Split. Must be one of 'control', 'train', 'public_test', or\
          \ 'private_test'"
        required: true
      - name: "control"
        type: "boolean"
        description: "Boolean indicating whether this instance was used as a control."
        required: true
    example:
    - "resources/neurips-2023-data/de_train.parquet"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--de_test"
    info:
      label: "DE test"
      summary: "Differential expression results for testing."
      file_type: "parquet"
      columns:
      - name: "id"
        type: "integer"
        description: "Index of the test observation"
        required: true
      - name: "cell_type"
        type: "string"
        description: "The annotated cell type of each cell based on RNA expression."
        required: true
      - name: "sm_name"
        type: "string"
        description: "The primary name for the (parent) compound (in a standardized\
          \ representation)\nas chosen by LINCS. This is provided to map the data\
          \ in this experiment to \nthe LINCS Connectivity Map data.\n"
        required: true
      - name: "sm_lincs_id"
        type: "string"
        description: "The global LINCS ID (parent) compound (in a standardized representation).\n\
          This is provided to map the data in this experiment to the LINCS Connectivity\n\
          Map data.\n"
        required: true
      - name: "SMILES"
        type: "string"
        description: "Simplified molecular-input line-entry system (SMILES) representations\
          \ of the\ncompounds used in the experiment. This is a 1D representation\
          \ of molecular\nstructure. These SMILES are provided by Cellarity based\
          \ on the specific\ncompounds ordered for this experiment.\n"
        required: true
      - name: "split"
        type: "string"
        description: "Split. Must be one of 'control', 'train', 'public_test', or\
          \ 'private_test'"
        required: true
      - name: "control"
        type: "boolean"
        description: "Boolean indicating whether this instance was used as a control."
        required: true
    example:
    - "resources/neurips-2023-data/de_test.parquet"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--id_map"
    info:
      label: "ID Map"
      summary: "File indicates the order of de_test, the cell types and the small\
        \ molecule names."
      file_type: "csv"
      columns:
      - name: "id"
        type: "integer"
        description: "Index of the test observation"
        required: true
      - name: "cell_type"
        type: "string"
        description: "Cell type name"
        required: true
      - name: "sm_name"
        type: "string"
        description: "Small molecule name"
        required: true
    example:
    - "resources/neurips-2023-data/id_map.csv"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    info:
      label: "Prediction"
      summary: "Differential Gene Expression prediction"
      file_type: "parquet"
      columns:
      - name: "id"
        type: "integer"
        description: "Index of the test observation"
        required: true
    example:
    - "resources/neurips-2023-data/prediction.parquet"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  test_resources:
  - type: "python_script"
    path: "src/common/component_tests/run_and_check_output.py"
    is_executable: true
  - type: "file"
    path: "resources/neurips-2023-data"
    dest: "resources/neurips-2023-data"
  info:
    label: "Mean outcome for a gene"
    summary: "Baseline method that returns mean of gene's outcomes"
    description: "Baseline method that predicts for a gene the mean of its outcomes\
      \ of all samples.\n"
    type: "control_method"
    type_info:
      label: "Control Method"
      summary: "A control method."
      description: "A control method to predict perturbation effects.\n"
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/openproblems-bio/base_python:1.0.2"
  target_organization: "openproblems-bio/task-dge-perturbation-prediction"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openproblems-bio/task-dge-perturbation-prediction"
  setup:
  - type: "python"
    user: false
    packages:
    - "fastparquet"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "highmem"
    - "highcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/src/task/control_methods/mean_outcome/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/target/nextflow/control_methods/mean_outcome"
  executable: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/target/nextflow/control_methods/mean_outcome/mean_outcome"
  viash_version: "0.8.5"
  git_commit: "1d2323716c4faff6a7ed38aa220e0203bb8b675b"
  git_remote: "https://github.com/openproblems-bio/task-dge-perturbation-prediction"
