n_components_list: # targets dimension list
  - 18211
d_models_list:
  - 128
batch_size: 32
sampling_strategy: k-means  # Choose either 'k-means' or 'random'
data_file: "/gpfs/gibbs/pi/zhao/tl688/single_cell_pb/de_train.parquet"
id_map_file: "/gpfs/gibbs/pi/zhao/tl688/single_cell_pb/id_map.csv"
validation_percentage: 0.1
device: cuda
seed: null
num_epochs: 1 #20000
early_stopping: 5000