__merge__: ../../api/comp_metric.yaml
functionality:
  name: mean_rowwise_rmse
  info:
    metrics:
      - name: mean_rowwise_rmse
        label: Mean Rowwise RMSE
        summary: The mean of the root mean squared error (RMSE) of each row in the matrix.
        description: |
          We use the **Mean Rowwise Root Mean Squared Error** to score submissions, computed as follows:

          $$
          \textrm{MRRMSE} = \frac{1}{R}\sum\_{i=1}^R\left(\frac{1}{n} \sum\_{j=1}^{n} (y\_{ij} - \widehat{y}\_{ij})^2\right)^{1/2}
          $$

          where \\(R\\) is the number of scored rows, and \\(y_{ij}\\) and \\(\widehat{y}_{ij}\\) are the actual and predicted values, respectively, for row \\(i\\) and column \\(j\\), and \\(n\\) is the number of columns.
        repository_url: "..."
        documentation_url: "..."
        min: 0
        max: "+inf"
        maximize: false
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.2
    setup:
      - type: python
        packages: [ fastparquet ]
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]