functionality:
  name: "scape"
  namespace: "methods"
  version: "main_build"
  arguments:
  - type: "file"
    name: "--de_train_h5ad"
    info:
      label: "DE train"
      summary: "Differential expression results for training."
      file_type: "h5ad"
      slots:
        obs:
        - name: "cell_type"
          type: "string"
          description: "The annotated cell type of each cell based on RNA expression."
          required: true
        - name: "sm_name"
          type: "string"
          description: "The primary name for the (parent) compound (in a standardized\
            \ representation)\nas chosen by LINCS. This is provided to map the data\
            \ in this experiment to \nthe LINCS Connectivity Map data.\n"
          required: true
        - name: "sm_lincs_id"
          type: "string"
          description: "The global LINCS ID (parent) compound (in a standardized representation).\n\
            This is provided to map the data in this experiment to the LINCS Connectivity\n\
            Map data.\n"
          required: true
        - name: "SMILES"
          type: "string"
          description: "Simplified molecular-input line-entry system (SMILES) representations\
            \ of the\ncompounds used in the experiment. This is a 1D representation\
            \ of molecular\nstructure. These SMILES are provided by Cellarity based\
            \ on the specific\ncompounds ordered for this experiment.\n"
          required: true
        - name: "split"
          type: "string"
          description: "Split. Must be one of 'control', 'train', 'public_test', or\
            \ 'private_test'"
          required: true
        - name: "control"
          type: "boolean"
          description: "Boolean indicating whether this instance was used as a control."
          required: true
        layers:
        - name: "logFC"
          type: "double"
          description: "Log fold change of the differential expression test"
          required: true
        - name: "AveExpr"
          type: "double"
          description: "Average expression of the differential expression test"
          required: false
        - name: "t"
          type: "double"
          description: "T-statistic of the differential expression test"
          required: false
        - name: "P.Value"
          type: "double"
          description: "P-value of the differential expression test"
          required: true
        - name: "adj.P.Value"
          type: "double"
          description: "Adjusted P-value of the differential expression test"
          required: true
        - name: "B"
          type: "double"
          description: "B-statistic of the differential expression test"
          required: false
        - name: "is_de"
          type: "boolean"
          description: "Whether the gene is differentially expressed"
          required: true
        - name: "is_de_adj"
          type: "boolean"
          description: "Whether the gene is differentially expressed after adjustment"
          required: true
        - name: "sign_log10_pval"
          type: "double"
          description: "Differential expression value (`-log10(p-value) * sign(LFC)`)\
            \ for each gene.\nHere, LFC is the estimated log-fold change in expression\
            \ between the treatment\nand control condition after shrinkage as calculated\
            \ by Limma. Positive LFC means\nthe gene goes up in the treatment condition\
            \ relative to the control.\n"
          required: true
        - name: "clipped_sign_log10_pval"
          type: "double"
          description: "A clipped version of the sign_log10_pval layer. Values are\
            \ clipped to be between\n-4 and 4 (i.e. `-log10(0.0001)` and `-log10(0.0001)`).\n"
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset. This is different from\
            \ the `obs.dataset_id` field, which is the identifier for the dataset\
            \ from which the cell data is derived."
          required: true
        - name: "dataset_name"
          type: "string"
          description: "A human-readable name for the dataset."
          required: true
        - type: "string"
          name: "dataset_url"
          description: "Link to the original source of the dataset."
          required: false
        - name: "dataset_reference"
          type: "string"
          description: "Bibtex reference of the paper in which the dataset was published."
          required: false
          multiple: true
        - name: "dataset_summary"
          type: "string"
          description: "Short description of the dataset."
          required: true
        - name: "dataset_description"
          type: "string"
          description: "Long description of the dataset."
          required: true
        - name: "dataset_organism"
          type: "string"
          description: "The organism of the sample in the dataset."
          required: false
          multiple: true
        - name: "single_cell_obs"
          type: "dataframe"
          description: "A dataframe with the cell-level metadata for the training\
            \ set.\n"
          required: true
    example:
    - "resources/neurips-2023-data/de_train.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--id_map"
    info:
      label: "ID Map"
      summary: "File indicates the order of de_test, the cell types and the small\
        \ molecule names."
      file_type: "csv"
      columns:
      - name: "id"
        type: "integer"
        description: "Index of the test observation"
        required: true
      - name: "cell_type"
        type: "string"
        description: "Cell type name"
        required: true
      - name: "sm_name"
        type: "string"
        description: "Small molecule name"
        required: true
    example:
    - "resources/neurips-2023-data/id_map.csv"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--layer"
    description: "Which layer to use for prediction."
    info: null
    default:
    - "clipped_sign_log10_pval"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    info:
      label: "Prediction"
      summary: "Differential Gene Expression prediction"
      file_type: "h5ad"
      slots:
        layers:
        - name: "prediction"
          type: "double"
          description: "Predicted differential gene expression"
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset. This is different from\
            \ the `obs.dataset_id` field, which is the identifier for the dataset\
            \ from which the cell data is derived."
          required: true
        - type: "string"
          name: "method_id"
          description: "A unique identifier for the method used to generate the prediction."
          required: true
    example:
    - "resources/neurips-2023-data/prediction.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_model"
    info:
      label: "Model"
      summary: "Optional model output. If no value is passed, the model will be removed\
        \ at the end of the run."
      file_type: "directory"
    example:
    - "resources/neurips-2023-data/model"
    must_exist: false
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--cell"
    description: "Pre-defined cell type held for pre-training."
    info: null
    default:
    - "NK cells"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--epochs"
    description: "Number of epochs for coarse training."
    info:
      test_default: 2
    default:
    - 300
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--epochs_enhanced"
    description: "Number of epochs for enhanced training."
    info:
      test_default: 2
    default:
    - 800
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--n_genes"
    description: "The number of genes for coarse training."
    info:
      test_default: 10
    default:
    - 64
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--n_genes_enhanced"
    description: "The number of genes for enhanced training."
    info:
      test_default: 10
    default:
    - 256
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--n_drugs"
    description: "The number of drugs to consider for coarse training. If none, all\
      \ drugs are considered."
    info:
      test_default: 5
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--min_n_top_drugs"
    description: "The minimum number of top drugs to consider."
    info:
      test_default: 0
    default:
    - 50
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  test_resources:
  - type: "python_script"
    path: "src/common/component_tests/run_and_check_output.py"
    is_executable: true
  - type: "file"
    path: "resources/neurips-2023-data"
    dest: "resources/neurips-2023-data"
  info:
    label: "ScAPE"
    neurips2023_rank: 16
    summary: "Neural network model for drug effect prediction"
    description: "ScAPE is utilises a neural network (NN) model to estimate drug effects\
      \ on gene expression in\nperipheral blood mononuclear cells (PBMCs). The model\
      \ took drug and cell features as input,\nwith these features primarily derived\
      \ from the median of signed log-pvalues and log fold-changes\ngrouped by drug\
      \ and cell type. The NN was trained using a leave-one-drug-out cross-validation\n\
      strategy, focusing on NK cells as a representative cell type due to their similarity\
      \ to B cells\nand Myeloid cells in principal component analysis. Model performance\
      \ was evaluated by comparing\nits predictions against two baselines: predicting\
      \ zero effect and predicting the median\nlog-pvalue for each drug. The final\
      \ submission combined predictions from models trained on\ndifferent gene and\
      \ drug subsets, aiming to enhance overall prediction accuracy.\n"
    reference: "pablormier2023scape"
    documentation_url: "https://docs.google.com/document/d/1w0GIJ8VoQx3HEJNmLXoU-Y_STB-h5-bXusL80_6EVuU/edit"
    repository_url: "https://github.com/scapeML/scape"
    type: "method"
    type_info:
      label: "Method"
      summary: "A regression method."
      description: "A regression method to predict the expression of one modality\
        \ from another.\n"
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "nvcr.io/nvidia/tensorflow:24.03-tf2-py3"
  target_organization: "openproblems-bio/task_perturbation_prediction"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openproblems-bio/task_perturbation_prediction"
  setup:
  - type: "apt"
    packages:
    - "procps"
    interactive: false
  - type: "python"
    user: false
    packages:
    - "anndata~=0.8.0"
    - "scanpy"
    - "pyyaml"
    - "requests"
    - "jsonschema"
    upgrade: true
  - type: "python"
    user: false
    packages:
    - "tensorflow-io-gcs-filesystem>=0.31.0"
    - "scikit-learn~=1.2.2"
    - "fastparquet~=2023.10.1"
    - "git+https://github.com/scapeML/scape.git"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "hightime"
    - "highmem"
    - "highcpu"
    - "gpu"
    - "midsharedmem"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task_perturbation_prediction/task_perturbation_prediction/src/methods/scape/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/task_perturbation_prediction/task_perturbation_prediction/target/docker/methods/scape"
  executable: "/home/runner/work/task_perturbation_prediction/task_perturbation_prediction/target/docker/methods/scape/scape"
  viash_version: "0.8.6"
  git_commit: "aaa0ca579115d226cac9577d7da1c1c60ff6c031"
  git_remote: "https://github.com/openproblems-bio/task_perturbation_prediction"
