__merge__: ../../api/comp_control_method.yaml
functionality:
  name: baseline_zero
  info:
    label: Zero baseline
    summary: Baseline method that predicts no change for any gene.
    description: Baseline.
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.2
    setup:
      - type: python
        packages: [ fastparquet ]
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]