functionality:
  name: initial_dataset_split
  namespace: dge_perturbation_prediction/process_dataset
  info:
    type: process_dataset
    type_info:
      label: Initial dataset split
      summary: Split the data for limma
      description: |
        Split the dataset before passing it separately for limma processing to avoid data leakage.
  arguments:
    - name: --input
      type: file
      required: true
      direction: input
      example: resources/neurips-2023-data/pseudobulk.h5ad
    - name: --output_train
      type: file
      required: true
      direction: output
      example: resources/neurips-2023-data/pseudobulk_train.h5ad
    - name: --output_test_celltypes
      type: file
      required: true
      direction: output
      example: resources/neurips-2023-data/pseudobulk_test_celltypes.h5ad
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.2
    setup:
      - type: python
        packages: [ fastparquet, anndata, pandas ]
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
