__merge__: ../../api/comp_metric.yaml
functionality:
  name: mean_rowwise_absolute_error
  info:
    metrics:
      - name: mean_rowwise_absolute_error
        label: Mean Rowwise Absolute Error (MRAE)
        summary: The mean of the absolute error (MAE) of each row in the matrix.
        description: |
            We use the **Mean Rowwise Absolute Error** to score submissions, computed as follows:

            $$
            \textrm{MRAE} = \frac{1}{R}\sum_{i=1}^R\left(\frac{1}{n} \sum_{j=1}^{n} |y_{ij} - \widehat{y}_{ij}|\right)
            $$
          
            where \(R\) is the number of scored rows, and \(y_{ij}\) and \(\widehat{y}_{ij}\) are the actual and predicted values, respectively, for row \(i\) and column \(j\), and \(n\) is the number of columns.
        repository_url: "..."
        documentation_url: "..."
        min: 0
        max: "+inf"
        maximize: false
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.2
    setup:
      - type: python
        packages: [ fastparquet ]
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]