__merge__: ../../api/comp_method.yaml
functionality:
  name: scape
  info:
    label: ScAPE
    summary: judge_2
    description: ScAPE is a package implementing the neural network model used in the Open Problems – Single-Cell Perturbations challenge hosted by Kaggle. This is the model we used to generate the submission that achieved top <2% performance (16th position out of 1097 teams) in the final leaderboard.
    reference: pablormier2023scape
    documentation_url: https://github.com/scapeML/scape
    repository_url: https://github.com/scapeML/scape
    preferred_normalization: counts
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: native
