functionality:
  name: run_limma
  namespace: dge_perturbation_prediction/process_dataset
  info:
    type: process_dataset
    type_info:
      label: Limma
      summary: Run limma
      description: |
        Run limma for the DGE regression task.
  arguments:
    - name: --input
      type: file
      required: true
      direction: input
    - name: --output
      type: file
      required: true
      direction: output
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.2
    setup:
      - type: r
        bioc: [ edgeR, limma ]
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
