__merge__: ../../api/comp_method.yaml

functionality:
  name: ambros_m_judges_third_place
  info:
    label: An ensemble model developed by competitor AmbrosM
    summary: "Ensemble comprised of four models: a py-boost model, an ExtraTrees model, and two recommender system models."
    documentation_url: https://www.kaggle.com/competitions/open-problems-single-cell-perturbations/discussion/458661
    repository_url: https://github.com/Ambros-M/Single-Cell-Perturbations-2023
  arguments:
    - type: integer
      name: --n_replica
      default: 10
      info:
        test_default: 1
    - type: string
      name: --submission_names
      multiple: true
      default: [dl40, dl200]
      info:
        test_default: [dl40]
  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages:
          - anndata==0.10.3
          - array-api-compat==1.4
          - async-generator==1.10
          - cupy-cuda11x==12.2.0
          - exceptiongroup==1.2.0
          - fastrlock==0.8.2
          - llvmlite==0.39.1
          - natsort==8.4.0
          - pandas==2.0.0
          - plotly==5.18.0
          - py-boost==0.4.3
          - pyarrow==14.0.1
          - pynndescent==0.5.11
          - scanpy==1.9.6
          - scipy==1.10.1
          - session-info==1.0.0
          - stdlib-list==0.10.0
          - tenacity==8.2.3
          - treelite==3.9.1
          - treelite-runtime==3.9.1
          - umap-learn==0.5.5
  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu,gpu]