functionality:
  name: "workflow"
  namespace: "process_dataset"
  version: "main_build"
  arguments:
  - type: "file"
    name: "--sc_counts"
    info:
      label: "Single Cell Counts"
      summary: "Anndata with the counts of the whole dataset."
      file_type: "h5ad"
      slots:
        obs:
        - name: "dose_uM"
          description: "Dose in micromolar."
          type: "integer"
          required: true
        - name: "timepoint_hr"
          description: "Time point measured in hours."
          type: "float"
          required: true
        - name: "raw_cell_id"
          description: "Original cell identifier."
          type: "string"
          required: true
        - name: "hashtag_id"
          description: "Identifier for hashtag oligo."
          type: "string"
          required: true
        - name: "well"
          description: "Well location in the plate."
          type: "string"
          required: true
        - name: "container_format"
          description: "Format of the container (e.g., 96-well plate)."
          type: "string"
          required: true
        - name: "row"
          description: "Row in the plate."
          type: "string"
          required: true
        - name: "col"
          description: "Column in the plate."
          type: "integer"
          required: true
        - name: "plate_name"
          description: "Name of the plate."
          type: "string"
          required: true
        - name: "cell_id"
          description: "Unique cell identifier."
          type: "string"
          required: true
        - name: "cell_type"
          description: "Type of cell (e.g., B cells, T cells CD4+)."
          type: "string"
          required: true
        - name: "split"
          description: "Dataset split type (e.g., control, treated)."
          type: "string"
          required: true
        - name: "donor_id"
          description: "Identifier for the donor."
          type: "string"
          required: true
        - name: "sm_name"
          description: "Name of the small molecule used for treatment."
          type: "string"
          required: true
        obsm:
        - name: "HTO_clr"
          description: "Corrected counts for hashing tags."
          type: "matrix"
          required: true
        - name: "X_pca"
          description: "Principal component analysis results."
          type: "matrix"
          required: true
        - name: "X_umap"
          description: "UMAP dimensionality reduction results."
          type: "matrix"
          required: true
        - name: "protein_counts"
          description: "Count data for proteins."
          type: "matrix"
          required: true
        layers:
        - name: "counts"
          description: "Raw count data for each gene across cells."
          type: "matrix"
          required: true
    example:
    - "resources/neurips-2023-raw/sc_counts.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--lincs_id_compound_mapping"
    info:
      label: "Mapping compound names to lincs ids and smiles"
      summary: "Parquet file mapping compound names to lincs ids and smiles."
      file_type: "parquet"
      columns:
      - name: "compound_id"
        description: "Unique identifier for the compound."
        type: "string"
        required: true
      - name: "sm_lincs_id"
        description: "LINCS identifier for the compound."
        type: "string"
        required: true
      - name: "sm_name"
        description: "Name of the compound."
        type: "string"
        required: true
      - name: "smiles"
        description: "SMILES notation representing the molecular structure."
        type: "string"
        required: true
    example:
    - "resources/neurips-2023-raw/lincs_id_compound_mapping.parquet"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--de_train"
    info:
      label: "DE train"
      summary: "Differential expression results for training."
      file_type: "parquet"
      columns:
      - name: "cell_type"
        type: "string"
        description: "The annotated cell type of each cell based on RNA expression."
        required: true
      - name: "sm_name"
        type: "string"
        description: "The primary name for the (parent) compound (in a standardized\
          \ representation)\nas chosen by LINCS. This is provided to map the data\
          \ in this experiment to \nthe LINCS Connectivity Map data.\n"
        required: true
      - name: "sm_lincs_id"
        type: "string"
        description: "The global LINCS ID (parent) compound (in a standardized representation).\n\
          This is provided to map the data in this experiment to the LINCS Connectivity\n\
          Map data.\n"
        required: true
      - name: "SMILES"
        type: "string"
        description: "Simplified molecular-input line-entry system (SMILES) representations\
          \ of the\ncompounds used in the experiment. This is a 1D representation\
          \ of molecular\nstructure. These SMILES are provided by Cellarity based\
          \ on the specific\ncompounds ordered for this experiment.\n"
        required: true
      - name: "split"
        type: "string"
        description: "Split. Must be one of 'control', 'train', 'public_test', or\
          \ 'private_test'"
        required: true
      - name: "control"
        type: "boolean"
        description: "Boolean indicating whether this instance was used as a control."
        required: true
    example:
    - "resources/neurips-2023-data/de_train.parquet"
    default:
    - "de_train.parquet"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--de_test"
    info:
      label: "DE test"
      summary: "Differential expression results for testing."
      file_type: "parquet"
      columns:
      - name: "id"
        type: "integer"
        description: "Index of the test observation"
        required: true
      - name: "cell_type"
        type: "string"
        description: "The annotated cell type of each cell based on RNA expression."
        required: true
      - name: "sm_name"
        type: "string"
        description: "The primary name for the (parent) compound (in a standardized\
          \ representation)\nas chosen by LINCS. This is provided to map the data\
          \ in this experiment to \nthe LINCS Connectivity Map data.\n"
        required: true
      - name: "sm_lincs_id"
        type: "string"
        description: "The global LINCS ID (parent) compound (in a standardized representation).\n\
          This is provided to map the data in this experiment to the LINCS Connectivity\n\
          Map data.\n"
        required: true
      - name: "SMILES"
        type: "string"
        description: "Simplified molecular-input line-entry system (SMILES) representations\
          \ of the\ncompounds used in the experiment. This is a 1D representation\
          \ of molecular\nstructure. These SMILES are provided by Cellarity based\
          \ on the specific\ncompounds ordered for this experiment.\n"
        required: true
      - name: "split"
        type: "string"
        description: "Split. Must be one of 'control', 'train', 'public_test', or\
          \ 'private_test'"
        required: true
      - name: "control"
        type: "boolean"
        description: "Boolean indicating whether this instance was used as a control."
        required: true
    example:
    - "resources/neurips-2023-data/de_test.parquet"
    default:
    - "de_test.parquet"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--id_map"
    info:
      label: "ID Map"
      summary: "File indicates the order of de_test, the cell types and the small\
        \ molecule names."
      file_type: "csv"
      columns:
      - name: "id"
        type: "integer"
        description: "Index of the test observation"
        required: true
      - name: "cell_type"
        type: "string"
        description: "Cell type name"
        required: true
      - name: "sm_name"
        type: "string"
        description: "Small molecule name"
        required: true
    example:
    - "resources/neurips-2023-data/id_map.csv"
    default:
    - "id_map.csv"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--dataset_id"
    description: "Unique identifier of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--dataset_name"
    description: "Nicely formatted name."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--dataset_url"
    description: "Link to the original source of the dataset."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--dataset_reference"
    description: "Bibtex reference of the paper in which the dataset was published."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--dataset_summary"
    description: "Short description of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--dataset_description"
    description: "Long description of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--dataset_organism"
    description: "The organism of the dataset."
    info: null
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--dataset_info"
    description: "A yaml file containing the dataset information."
    info: null
    default:
    - "dataset_info.yaml"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  info:
    type: "process_dataset"
    type_info:
      label: "Process dataset"
      summary: "Process the raw dataset"
      description: "Process the raw dataset for the DGE regression task.\n"
  status: "enabled"
  dependencies:
  - name: "process_dataset/clean_sc_counts"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/src/task/process_dataset/clean_sc_counts/config.vsh.yaml"
    configInfo:
      functionalityName: "clean_sc_counts"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task-dge-perturbation-prediction"
      viash_version: "0.8.5"
      config: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/src/task/process_dataset/clean_sc_counts/config.vsh.yaml"
      functionalityNamespace: "process_dataset"
      output: ""
      platform: ""
      git_commit: "8a458177370e73a03f680cb2a796e80cd51c8a86"
      executable: "/nextflow/process_dataset/clean_sc_counts/main.nf"
    writtenPath: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/target/nextflow/process_dataset/clean_sc_counts"
  - name: "process_dataset/compute_pseudobulk"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/src/task/process_dataset/compute_pseudobulk/config.vsh.yaml"
    configInfo:
      functionalityName: "compute_pseudobulk"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task-dge-perturbation-prediction"
      viash_version: "0.8.5"
      config: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/src/task/process_dataset/compute_pseudobulk/config.vsh.yaml"
      functionalityNamespace: "process_dataset"
      output: ""
      platform: ""
      git_commit: "8a458177370e73a03f680cb2a796e80cd51c8a86"
      executable: "/nextflow/process_dataset/compute_pseudobulk/main.nf"
    writtenPath: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/target/nextflow/process_dataset/compute_pseudobulk"
  - name: "process_dataset/run_limma"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/src/task/process_dataset/run_limma/config.vsh.yaml"
    configInfo:
      functionalityName: "run_limma"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task-dge-perturbation-prediction"
      viash_version: "0.8.5"
      config: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/src/task/process_dataset/run_limma/config.vsh.yaml"
      functionalityNamespace: "process_dataset"
      output: ""
      platform: ""
      git_commit: "8a458177370e73a03f680cb2a796e80cd51c8a86"
      executable: "/nextflow/process_dataset/run_limma/main.nf"
    writtenPath: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/target/nextflow/process_dataset/run_limma"
  - name: "process_dataset/convert_h5ad_to_parquet"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/src/task/process_dataset/convert_h5ad_to_parquet/config.vsh.yaml"
    configInfo:
      functionalityName: "convert_h5ad_to_parquet"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task-dge-perturbation-prediction"
      viash_version: "0.8.5"
      config: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/src/task/process_dataset/convert_h5ad_to_parquet/config.vsh.yaml"
      functionalityNamespace: "process_dataset"
      output: ""
      platform: ""
      git_commit: "8a458177370e73a03f680cb2a796e80cd51c8a86"
      executable: "/nextflow/process_dataset/convert_h5ad_to_parquet/main.nf"
    writtenPath: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/target/nextflow/process_dataset/convert_h5ad_to_parquet"
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "lowcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/src/task/process_dataset/workflow/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/target/nextflow/process_dataset/workflow"
  executable: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/target/nextflow/process_dataset/workflow/main.nf"
  viash_version: "0.8.5"
  git_commit: "8a458177370e73a03f680cb2a796e80cd51c8a86"
  git_remote: "https://github.com/openproblems-bio/task-dge-perturbation-prediction"
