__merge__: ../../api/comp_metric.yaml
functionality:
  name: mean_correlation
  info:
    metrics:
      - name: mean_pearson
        label: Mean Pearson
        summary: The mean of Pearson correlations per row (perturbation).
        description: |
          We use the **Mean Pearson Correlation** to score submissions.
        repository_url: null
        documentation_url: null
        min: -1
        max: 1
        maximize: true
      - name: mean_spearman
        label: Mean Spearman
        summary: The mean of Spearman correlations per row (perturbation).
        description: |
          We use the **Mean Spearman Correlation** to score submissions.
        repository_url: null
        documentation_url: null
        min: -1
        max: 1
        maximize: true
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [ fastparquet ]
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]