functionality:
  name: "convert_h5ad_to_parquet"
  namespace: "process_dataset"
  version: "main_build"
  arguments:
  - type: "file"
    name: "--input_train"
    info: null
    example:
    - "resources/neurips-2023-data/de_train.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--input_test"
    info: null
    example:
    - "resources/neurips-2023-data/de_test.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_train"
    info: null
    example:
    - "resources/neurips-2023-data/de_train.parquet"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_test"
    info: null
    example:
    - "resources/neurips-2023-data/de_test.parquet"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_id_map"
    info: null
    example:
    - "resources/neurips-2023-data/id_map.csv"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  info:
    type: "process_dataset"
    type_info:
      label: "Split dataset"
      summary: "Split dataset into training and test parquet files"
      description: "Split dataset into training and test parquet files.\n"
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/openproblems-bio/base_python:1.0.2"
  target_organization: "openproblems-bio/task-dge-perturbation-prediction"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openproblems-bio/task-dge-perturbation-prediction"
  setup:
  - type: "python"
    user: false
    packages:
    - "fastparquet"
    - "anndata"
    - "pandas"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "lowcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/src/task/process_dataset/convert_h5ad_to_parquet/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/target/nextflow/process_dataset/convert_h5ad_to_parquet"
  executable: "/home/runner/work/task-dge-perturbation-prediction/task-dge-perturbation-prediction/target/nextflow/process_dataset/convert_h5ad_to_parquet/convert_h5ad_to_parquet"
  viash_version: "0.8.5"
  git_commit: "00b03a0a115b46d545e0f0797beb3f7f67d2ad21"
  git_remote: "https://github.com/openproblems-bio/task-dge-perturbation-prediction"
