__merge__: ../../api/comp_control_method.yaml
functionality:
  name: mean_across_celltypes
  info:
    label: Mean outcome for the cell type
    summary: Baseline method that returns mean of cell type's outcomes
    description: |
      Baseline method that predicts for a cell type the mean of its outcomes of all compounds.
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.2
    setup:
      - type: python
        packages: [ fastparquet ]
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]