__merge__: ../../api/comp_process_dataset.yaml
functionality:
  name: workflow
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  dependencies:
    - name: process_dataset/clean_sc_counts
    - name: process_dataset/compute_pseudobulk
    - name: process_dataset/run_limma
    - name: process_dataset/convert_h5ad_to_parquet
platforms:
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
