functionality:
  name: workflow
  namespace: process_dataset
  info:
    type: process_dataset
    type_info:
      label: Workflow
      summary: Process the raw dataset
      description: |
        Process the raw dataset for the DGE regression task.
  arguments:
    - name: --sc_counts
      type: file
      required: true
      direction: input
      example: resources/neurips-2023-raw/sc_counts.h5ad
    - name: --lincs_id_compound_mapping
      type: file
      required: true
      direction: input
      example: resources/neurips-2023-raw/lincs_id_compound_mapping.parquet
    - name: --pseudobulk
      type: file
      required: true
      direction: output
      example: resources/neurips-2023-data/pseudobulk.h5ad
    - name: --de_train_h5ad
      type: file
      required: true
      direction: output
      example: resources/neurips-2023-data/de_train.h5ad
    - name: --de_test_h5ad
      type: file
      required: true
      direction: output
      example: resources/neurips-2023-data/de_test.h5ad
    - name: --de_train_parquet
      type: file
      required: true
      direction: output
      example: resources/neurips-2023-data/de_train.parquet
    - name: --de_test_parquet
      type: file
      required: true
      direction: output
      example: resources/neurips-2023-data/de_test.parquet
    - name: --id_map
      type: file
      required: true
      direction: output
      example: resources/neurips-2023-data/id_map.csv
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  dependencies:
    - name: dge_perturbation_prediction/process_dataset/clean_sc_counts
    - name: dge_perturbation_prediction/process_dataset/compute_pseudobulk
    - name: dge_perturbation_prediction/process_dataset/run_limma
    - name: dge_perturbation_prediction/process_dataset/convert_h5ad_to_parquet
platforms:
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
