functionality:
  name: clean_pseudobulk
  namespace: process_dataset
  info:
    type: process_dataset
    type_info:
      label: Filter pseudobulked data
      summary: Filter the genes and compounds
      description: |
        Filter the pseudobulked single-cell dataset for the DGE regression task.
  arguments:
    - name: --input
      type: file
      required: true
      direction: input
      example: resources/neurips-2023-raw/pseudobulk.h5ad
    - name: --output
      type: file
      required: true
      direction: output
      example: resources/neurips-2023-data/pseudobulk_cleaned.h5ad
  resources:
    - type: python_script
      path: script.py
    - path: filter_genes.R
platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.2
    setup:
      - type: python
        packages: [ pyarrow ]
      - type: r
        cran: [ edgeR, limma, dplyr, tidyr, purrr, tibble ]
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
